
// src/models/city/cities.schema.ts

// Type for creating a city, without autogenerated fields
interface ICitySchema {
    name: string;
    location: {
        long: number;
        lat: number;
    };
    createdAt?: Date; // Optional, auto-generated by Mongoose
}

export {
    ICitySchema,
}